version: '3.8'
services:
  web:
    build: .
    container_name: web
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_URL=postgresql://user:password@db/image_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "8000:8000"
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_db
    ports:
      - "5433:5432"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
